### ISSUE TITLE
Broken on Node.js v0.12

### ISSUE THREAD

**Issue by joepie91** [yjwong/node-sane#4]
Getting the following output when trying to install this library on 0.12, I suspect the API may have broken in some way?

```
sven@linux-etoq:~/projects/archivist> npm install yjwong/node-sane
npm WARN package.json archivist@1.0.0 No description
npm WARN package.json archivist@1.0.0 No README data
-
> sane@0.0.1 install /home/sven/projects/archivist/node_modules/sane
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/sven/projects/archivist/node_modules/sane/build'
  CXX(target) Release/obj.target/sane/src/sane.o
In file included from ../src/sane.cc:8:0:
../src/sane_device.h:7:44: error: expected class-name before ‘{’ token
 class SaneDevice : public node::ObjectWrap {
                                            ^
../src/sane_device.h:17:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetName (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_device.h:17:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetName (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_device.h:18:80: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetVendor (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                ^
../src/sane_device.h:18:98: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetVendor (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                  ^
../src/sane_device.h:19:79: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetModel (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                               ^
../src/sane_device.h:19:97: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetModel (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                 ^
../src/sane_device.h:20:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_device.h:20:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
In file included from ../src/sane.cc:9:0:
../src/sane_handle.h:7:44: error: expected class-name before ‘{’ token
 class SaneHandle : public node::ObjectWrap {
                                            ^
../src/sane_handle.h:12:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> New (const v8::Arguments& args);
                                          ^
../src/sane_handle.h:12:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> New (const v8::Arguments& args);
                                                         ^
In file included from ../src/sane.cc:10:0:
../src/sane_option_descriptor.h:7:54: error: expected class-name before ‘{’ token
 class SaneOptionDescriptor : public node::ObjectWrap {
                                                      ^
../src/sane_option_descriptor.h:17:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetName (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_option_descriptor.h:17:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetName (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_option_descriptor.h:18:79: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetTitle (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                               ^
../src/sane_option_descriptor.h:18:97: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetTitle (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                 ^
../src/sane_option_descriptor.h:19:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetDesc (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_option_descriptor.h:19:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetDesc (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_option_descriptor.h:20:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_option_descriptor.h:20:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_option_descriptor.h:21:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetUnit (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_option_descriptor.h:21:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetUnit (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_option_descriptor.h:22:78: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetSize (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                              ^
../src/sane_option_descriptor.h:22:96: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetSize (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                ^
../src/sane_option_descriptor.h:23:77: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetCap (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                             ^
../src/sane_option_descriptor.h:23:95: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetCap (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                               ^
../src/sane_option_descriptor.h:24:88: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetConstraintType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                        ^
../src/sane_option_descriptor.h:24:106: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetConstraintType (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                          ^
In file included from ../src/sane.cc:11:0:
../src/sane_parameters.h:7:48: error: expected class-name before ‘{’ token
 class SaneParameters : public node::ObjectWrap {
                                                ^
../src/sane_parameters.h:13:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> New (const v8::Arguments& args);
                                          ^
../src/sane_parameters.h:13:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> New (const v8::Arguments& args);
                                                         ^
../src/sane_parameters.h:15:14: error: ‘node::ObjectWrap’ has not been declared
  using node::ObjectWrap::Wrap;
              ^
../src/sane_parameters.h:21:80: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetFormat (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                ^
../src/sane_parameters.h:21:98: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetFormat (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                  ^
../src/sane_parameters.h:22:91: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetFormat (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                           ^
../src/sane_parameters.h:22:109: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetFormat (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                             ^
../src/sane_parameters.h:24:83: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetLastFrame (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                   ^
../src/sane_parameters.h:24:101: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetLastFrame (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                     ^
../src/sane_parameters.h:25:94: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetLastFrame (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                              ^
../src/sane_parameters.h:25:112: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetLastFrame (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                                ^
../src/sane_parameters.h:27:86: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetBytesPerLine (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                      ^
../src/sane_parameters.h:27:104: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetBytesPerLine (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                        ^
../src/sane_parameters.h:28:97: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetBytesPerLine (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                 ^
../src/sane_parameters.h:28:115: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetBytesPerLine (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                                   ^
../src/sane_parameters.h:30:87: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetPixelsPerLine (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                       ^
../src/sane_parameters.h:30:105: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetPixelsPerLine (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                         ^
../src/sane_parameters.h:31:98: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetPixelsPerLine (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                  ^
../src/sane_parameters.h:31:116: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetPixelsPerLine (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                                    ^
../src/sane_parameters.h:33:79: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetLines (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                               ^
../src/sane_parameters.h:33:97: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetLines (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                 ^
../src/sane_parameters.h:34:90: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetLines (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                          ^
../src/sane_parameters.h:34:108: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetLines (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                            ^
../src/sane_parameters.h:36:79: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> GetDepth (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                               ^
../src/sane_parameters.h:36:97: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static v8::Handle<v8::Value> GetDepth (v8::Local<v8::String> property, const v8::AccessorInfo& info);
                                                                                                 ^
../src/sane_parameters.h:37:90: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
  static void SetDepth (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                          ^
../src/sane_parameters.h:37:108: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
  static void SetDepth (v8::Local<v8::String> property, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
                                                                                                            ^
../src/sane.cc:21:13: error: ‘Arguments’ does not name a type
 Init (const Arguments& args) {
             ^
../src/sane.cc:21:24: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Init (const Arguments& args) {
                        ^
In file included from /usr/include/node/node.h:61:0,
                 from ../src/sane.cc:3:
/usr/include/node/v8.h: In function ‘v8::Handle<v8::Value> Init(const int&)’:
/usr/include/node/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/sane.cc:22:14: error: within this context
  HandleScope scope;
              ^
../src/sane.cc:26:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close (Number::New (status));
               ^
../src/sane.cc:26:41: error: no matching function for call to ‘v8::Number::New(SANE_Status&)’
  return scope.Close (Number::New (status));
                                         ^
../src/sane.cc:26:41: note: candidate is:
In file included from /usr/include/node/node.h:61:0,
                 from ../src/sane.cc:3:
/usr/include/node/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/usr/include/node/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/sane.cc: At global scope:
../src/sane.cc:30:13: error: ‘Arguments’ does not name a type
 Exit (const Arguments& args) {
             ^
../src/sane.cc:30:24: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Exit (const Arguments& args) {
                        ^
In file included from /usr/include/node/node.h:61:0,
                 from ../src/sane.cc:3:
/usr/include/node/v8.h: In function ‘v8::Handle<v8::Value> Exit(const int&)’:
/usr/include/node/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/sane.cc:31:14: error: within this context
  HandleScope scope;
              ^
../src/sane.cc:33:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
  return scope.Close (Undefined ());
               ^
../src/sane.cc:33:33: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
  return scope.Close (Undefined ());
                                 ^
In file included from /usr/include/node/node.h:61:0,
                 from ../src/sane.cc:3:
/usr/include/node/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/sane.cc: At global scope:
../src/sane.cc:37:2: error: ‘uv_work_t’ does not name a type
  uv_work_t request;
  ^
../src/sane.cc:46:27: error: variable or field ‘GetDevicesAsyncWork’ declared void
 void GetDevicesAsyncWork (uv_work_t* req) {
                           ^
../src/sane.cc:46:27: error: ‘uv_work_t’ was not declared in this scope
../src/sane.cc:46:38: error: ‘req’ was not declared in this scope
 void GetDevicesAsyncWork (uv_work_t* req) {
                                      ^
../src/sane.cc:51:28: error: variable or field ‘GetDevicesAsyncAfter’ declared void
 void GetDevicesAsyncAfter (uv_work_t* req) {
                            ^
../src/sane.cc:51:28: error: ‘uv_work_t’ was not declared in this scope
../src/sane.cc:51:39: error: ‘req’ was not declared in this scope
 void GetDevicesAsyncAfter (uv_work_t* req) {
                                       ^
../src/sane.cc: In function ‘v8::Handle<v8::Value> Init(const int&)’:
../src/sane.cc:27:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/sane.cc: In function ‘v8::Handle<v8::Value> Exit(const int&)’:
../src/sane.cc:34:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/sane/src/sane.o] Error 1
make: Leaving directory `/home/sven/projects/archivist/node_modules/sane/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.11.10-29-desktop
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sven/projects/archivist/node_modules/sane
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.11.10-29-desktop
npm ERR! argv "node" "/usr/bin/npm" "install" "yjwong/node-sane"
npm ERR! node v0.12.0
npm ERR! npm  v2.1.3
npm ERR! code ELIFECYCLE

npm ERR! sane@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sane@0.0.1 install script.
npm ERR! This is most likely a problem with the sane package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sane
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sven/projects/archivist/npm-debug.log
```

SANE development header package info:

```
sven@linux-etoq:~/projects/archivist> zypper info sane-backends-devel
Loading repository data...
Reading installed packages...


Information for package sane-backends-devel:
--------------------------------------------
Repository: graphics
Name: sane-backends-devel
Version: 1.0.24-111.6
Arch: x86_64
Vendor: obs://build.opensuse.org/graphics
Installed: Yes
Status: up-to-date
Installed Size: 31.1 KiB
Summary: Development files for sane-backends
Description: 
This package contains the development files for sane-backends.
```

**Comment by yjwong** [comment]
Finally had the time to fix everything up for newer versions of Node. Should be working on v0.12.x and v4.x already, so I'll close this issue.
